name: timeset
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.1.2
  flutter_native_splash: ^2.3.11
  hexcolor: ^3.0.1
  flutter_launcher_icons: ^0.13.1
  smooth_page_indicator: ^1.1.0
  shared_preferences: ^2.2.3
  sizer: ^2.0.15
  page_transition: ^2.1.0
  flutter_svg: ^2.0.10+1
  pinput: ^4.0.0
  http: ^1.2.0
  fluttertoast: ^8.2.5
  image_picker: ^1.1.1
  shimmer: ^3.0.0
  carousel_slider: ^4.2.1
  camera: ^0.10.0+1
  permission_handler: ^10.4.5
  visibility_detector: ^0.4.0+2
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  flutter_rating_bar: ^4.0.1
  readmore: ^3.0.0
  preload_page_view: ^0.2.0
  chewie: ^1.8.1
  video_player: ^2.8.6
  firebase_core: ^2.31.1
  firebase_storage: ^11.7.6


flutter_icons: # flutter_launcher_icons configuration
  android: "launcher_icon"
  ios: true
  image_path: "assets/logos/icon.png"
  min_sdk_android: 21

flutter_native_splash: # flutter_native_splash configuration
  color: "#141414"
  image: assets/logos/logo.png
  android: true
  ios: true
  web: false

  android_12:
    image: assets/logos/logo.png
    icon_background_color: "#141414"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/logos/
    - assets/images/

  fonts:
    - family: pjs
      fonts:
        - asset: fonts/PlusJakartaSans-Regular.ttf
          weight: 400

        - asset: fonts/PlusJakartaSans-SemiBold.ttf
          weight: 600

        - asset: fonts/PlusJakartaSans-Bold.ttf
          weight: 700

        - asset: fonts/PlusJakartaSans-Medium.ttf
          weight: 600

        - asset: fonts/PlusJakartaSans-ExtraBold.ttf
          weight: 900

        - asset: fonts/PlusJakartaSans-ExtraLight.ttf
          weight: 200

        - asset: fonts/PlusJakartaSans-Italic.ttf
          style: italic

        - asset: fonts/PlusJakartaSans-Light.ttf
          weight: 300
