// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8DwizlSXeBYfYiFFCQp9vbfjQx9OadWA',
    appId: '1:48668207952:web:bad022e45a722803605a55',
    messagingSenderId: '48668207952',
    projectId: 'timeset-aa5e9',
    authDomain: 'timeset-aa5e9.firebaseapp.com',
    storageBucket: 'timeset-aa5e9.appspot.com',
    measurementId: 'G-GD3DJ5NQGY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHxgulGz-oHkkbq1oTI_3ZXf5zuvNyW-s',
    appId: '1:48668207952:android:2bdcad12de52890c605a55',
    messagingSenderId: '48668207952',
    projectId: 'timeset-aa5e9',
    storageBucket: 'timeset-aa5e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNkJ5vJUxG53DyOmPxwjAEJgYq1KhYEfY',
    appId: '1:48668207952:ios:d6e3ecdc80c76a0d605a55',
    messagingSenderId: '48668207952',
    projectId: 'timeset-aa5e9',
    storageBucket: 'timeset-aa5e9.appspot.com',
    iosBundleId: 'com.example.timeset',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNkJ5vJUxG53DyOmPxwjAEJgYq1KhYEfY',
    appId: '1:48668207952:ios:d6e3ecdc80c76a0d605a55',
    messagingSenderId: '48668207952',
    projectId: 'timeset-aa5e9',
    storageBucket: 'timeset-aa5e9.appspot.com',
    iosBundleId: 'com.example.timeset',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8DwizlSXeBYfYiFFCQp9vbfjQx9OadWA',
    appId: '1:48668207952:web:72b40578507aa329605a55',
    messagingSenderId: '48668207952',
    projectId: 'timeset-aa5e9',
    authDomain: 'timeset-aa5e9.firebaseapp.com',
    storageBucket: 'timeset-aa5e9.appspot.com',
    measurementId: 'G-5XZ5CZ509Z',
  );
}
